### ISSUE TITLE
issue at starting up

### ISSUE THREAD

**Issue by unpluggedk** [doukasd/iOS-Components#5]
hi, i am using the multidialcontroller in one of my projects and i have encountered a small problem.
a weird one perhaps.

the problem is this:

i have this uiview class, say A, which has a multidialcontroller and i initialize this before adding it on to the main view.
i after this, i add this controller to the main view and it shows the controlller alright.

however, if i invoke spintorandom in viewdidappear, the device goes into a 'pause' mode and then gets a bad memory access.

funny thing is that when i do multiviewcontroller.dial4 selectString, before I do the spin, it works fine.
if i do dial1 ~3 it doesn't.

any suggestions ?

**Comment by unpluggedk** [comment]
my mistake. all working fine.
Thanks

**Comment by doukasd** [comment]
Ah, good to hear it!
